### ISSUE TITLE
ContextOptions are sticky after Exit/Relaunch

### ISSUE THREAD

**Issue by Snord9** [martinmimigames/little-file-explorer#27]
I mark a some items
a few ContextOption buttons appear

BUT we then Exit app
and Relaunch

ContextOptions from previous session are stcky, buy no object items are yet Marked

After a while, figured out to Cancel .. to get back to Norbal

**Comment by wmartinmimi** [comment]
Reproducable on my side, thank you for reporting.

**Comment by wmartinmimi** [comment]
Now fixed in Little File Explorer v4.9

You can download it via:
- [Github](https://github.com/martinmimigames/little-file-explorer/releases/tag/v4.9)
- [Official website](https://martinmimigames.github.io/projects/little-file-explorer/index.html)
- [F-droid](https://f-droid.org/packages/com.martinmimigames.simplefileexplorer/) (may take a while to update)
