### ISSUE TITLE
Delete window is huge

### ISSUE THREAD

**Issue by Cwpute** [martinmimigames/little-file-explorer#30]
The Delete window takes up the whole screen, compared to the Open window for example. It could probably be reduced in size to be more convenient :)
![Screenshot_20230601-144311](https://github.com/martinmimigames/little-file-explorer/assets/80604512/541dadc9-07fd-493e-b116-0a926cff5ca1)

**Comment by wmartinmimi** [comment]
Now fixed in latest code.
Fix should be available in next release.

**Comment by wmartinmimi** [comment]
Now fixed in Little File Explorer v4.10

You can download it via:
- [Github](https://github.com/martinmimigames/little-file-explorer/releases/tag/v4.10)
- [Official website](https://martinmimigames.github.io/projects/little-file-explorer/index.html)
- [F-droid](https://f-droid.org/packages/com.martinmimigames.simplefileexplorer/) (may take a while to update)
