### ISSUE TITLE
[Bug] App stops responding while opening details view for large files

### ISSUE THREAD

**Issue by shai8I** [martinmimigames/little-file-explorer#45]
**Description**

It stops responding until the details view opens. Larger files take longer.

Takes about a minute for a 1.6 GB file on a high end 2013 device.

**To reproduce**

1. Tap on a file, select "Details".
2. App stops responding until the details view shows.

**Some ideas**

Assuming it hangs while doing the hash, then perhaps the details screen can be shown first.

Alternatively, can have a manual "calculate md5" alongside the "copy" (or "copy md5"?) and "check clipboard" buttons.

Extra: something to indicate calculating and have it stop if the user closes the details screen.

**Version**
- App: 4.12
- OS: Android 13

**Comment by wmartinmimi** [comment]
Should now fixed in Little File Explorer v4.13

You can download it via:
- [Github](https://github.com/martinmimigames/little-file-explorer/releases/tag/v4.13)
- [Official website](https://martinmimigames.github.io/projects/little-file-explorer/)
- [F-droid](https://f-droid.org/packages/com.martinmimigames.simplefileexplorer/) (may take a while to update)
