### ISSUE TITLE
[Bug] Checking md5 hash against blank clipboard causes app to stop

### ISSUE THREAD

**Issue by shai8I** [martinmimigames/little-file-explorer#46]
**To Reproduce**

1. Clear the clipboard (via keyboard/ reboot/ etc.)
2. Tap on a file > Details > check clipboard.
3. App stops.

**Version**

- App: 4.12
- OS: Android 13

**Comment by wmartinmimi** [comment]
Should now fixed in Little File Explorer v4.13

You can download it via:
- [Github](https://github.com/martinmimigames/little-file-explorer/releases/tag/v4.13)
- [Official website](https://martinmimigames.github.io/projects/little-file-explorer/)
- [F-droid](https://f-droid.org/packages/com.martinmimigames.simplefileexplorer/) (may take a while to update)

**Comment by alexlostorto** [comment]
Close the issue then? @wmartinmimi
