### ISSUE TITLE
[Bug] Can't share files to "ffshare" app

### ISSUE THREAD

**Issue by Cwpute** [martinmimigames/little-file-explorer#62]
**Describe the bug**
Trying to share files to [ffshare](https://github.com/caydey/ffshare) fails a lot of times, with ffshare either sending a toast saying it did not recognize the file or format, or simply crashing.
If i try to send those same files to ffshare using another file browser (https://gitlab.com/axet/android-file-manager) it works without question. If i try to process those files from within ffshare using the built-in file browser, it works.

There must be something wrong in the way LFE communicates those files to ffshare.

**To Reproduce**
1. Download [ffshare](https://github.com/caydey/ffshare) 
2. Send any mp3, ogg, mp4… file to ffshare from within LFE
3. Witness ffshare struggling

**Expected Behaviour**
The files should be shared correctly.

**[Optional] Versioning  information**
- App Version 4.13
- OS: Android 11

**Comment by wmartinmimi** [comment]
#63 
related

**Comment by wmartinmimi** [comment]
Should now be fixed in Little File Explorer v4.14

You can download it via:
- [Github](https://github.com/martinmimigames/little-file-explorer/releases/tag/v4.14)
- [Official website](https://martinmimigames.github.io/projects/little-file-explorer/)
- [F-droid](https://f-droid.org/packages/com.martinmimigames.simplefileexplorer/) (may take a while to update)
